console.log("Welcome to Meri Kaksha");
fullName= " Sweta Mishra";
_fullName= " Vivek Thakur";
$fullName= " Mahi ";
age= 40;
price = 45;
x= null;
y= undefined;
isFollow = false;
console.log(y);
console.log(isFollow);
console.log(fullName);
console.log(_fullName);
console.log($fullName);